### ISSUE TITLE
Add more logging

### ISSUE THREAD

**Issue by albertus-andito** [PPIUK/ppi-portal-backend#25]
**Is your feature request related to a problem? Please describe.**
Currently, there is only minimum logging used. This makes it quite hard to solve issues in production.

**Describe the solution you'd like**
Utilise the Winston logger that has been created. Use it to log errors and in some crucial steps of every endpoint for information.

**Describe alternatives you've considered**

**Additional context**

**Comment by raka-gunarto** [comment]
How's this @albertus-andito

**Comment by raka-gunarto** [comment]
https://drive.google.com/file/d/1BePWXgr2lqZAj9TbV_PZqw49XaUUlEPy/view?usp=sharing 🤣

**Comment by albertus-andito** [comment]
LGTM! 🤣
