### ISSUE TITLE
Email should be case insensitive

### ISSUE THREAD

**Issue by albertus-andito** [PPIUK/ppi-portal-backend#26]
**Describe the bug**
Email fields are currently case sensitive when they should be case insensitive instead. This resulted in the possibility of having multiple accounts with the same email, submitted as two different emails with different cases. 

**To Reproduce**
1. Register using the /auth/registerNew endpoint with an email, for example aa@sussex.ac.uk
2. Register again using the same endpoint with the same email, but different case for some letters, for example Aa@sussex.ac.uk
3. You will still be able to successfully register the new account

**Expected behavior**
If there is already an account registered with the same email, although different cases, the registration should fail and user should be informed that the account already exists. Consequently, logging in should also be case insensitive.

**Screenshots**

**Additional context**
Production database needs to be sanitised, especially for the ones related with this issue.

**Comment by albertus-andito** [comment]
I have updated the code with the above commit.
Can I ask @raka-gunarto to clean the production database, please? Thanks

**Comment by raka-gunarto** [comment]
![image](https://user-images.githubusercontent.com/54971890/134107745-241a5f45-93ae-470b-b796-4bf071354185.png)

Cleaned :+1:
